// source: google/cloud/visionai/v1alpha1/lva.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AnalysisDefinition', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AttributeValue', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.AttributeValue.ValueCase', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.OperatorDefinition', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.ResourceSpecification', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.OperatorDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.displayName = 'proto.google.cloud.visionai.v1alpha1.OperatorDefinition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.displayName = 'proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.displayName = 'proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.ResourceSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.ResourceSpecification.displayName = 'proto.google.cloud.visionai.v1alpha1.ResourceSpecification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.AttributeValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.AttributeValue.displayName = 'proto.google.cloud.visionai.v1alpha1.AttributeValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.displayName = 'proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.displayName = 'proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.displayName = 'proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.AnalysisDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.displayName = 'proto.google.cloud.visionai.v1alpha1.AnalysisDefinition';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    operator: jspb.Message.getFieldWithDefault(msg, 1, ""),
    inputArgsList: jspb.Message.toObjectList(msg.getInputArgsList(),
    proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.toObject, includeInstance),
    outputArgsList: jspb.Message.toObjectList(msg.getOutputArgsList(),
    proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.toObject, includeInstance),
    attributesList: jspb.Message.toObjectList(msg.getAttributesList(),
    proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.toObject, includeInstance),
    resources: (f = msg.getResources()) && proto.google.cloud.visionai.v1alpha1.ResourceSpecification.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition;
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperator(value);
      break;
    case 2:
      var value = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.deserializeBinaryFromReader);
      msg.addInputArgs(value);
      break;
    case 3:
      var value = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.deserializeBinaryFromReader);
      msg.addOutputArgs(value);
      break;
    case 4:
      var value = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.deserializeBinaryFromReader);
      msg.addAttributes(value);
      break;
    case 5:
      var value = new proto.google.cloud.visionai.v1alpha1.ResourceSpecification;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.ResourceSpecification.deserializeBinaryFromReader);
      msg.setResources(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperator();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInputArgsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.serializeBinaryToWriter
    );
  }
  f = message.getOutputArgsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.serializeBinaryToWriter
    );
  }
  f = message.getAttributesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.serializeBinaryToWriter
    );
  }
  f = message.getResources();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.cloud.visionai.v1alpha1.ResourceSpecification.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    argument: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition;
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setArgument(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArgument();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string argument = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.getArgument = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.setArgument = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    attribute: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    defaultValue: (f = msg.getDefaultValue()) && proto.google.cloud.visionai.v1alpha1.AttributeValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition;
  return proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAttribute(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = new proto.google.cloud.visionai.v1alpha1.AttributeValue;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.AttributeValue.deserializeBinaryFromReader);
      msg.setDefaultValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttribute();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDefaultValue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.cloud.visionai.v1alpha1.AttributeValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string attribute = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.getAttribute = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.setAttribute = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional AttributeValue default_value = 3;
 * @return {?proto.google.cloud.visionai.v1alpha1.AttributeValue}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.getDefaultValue = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.AttributeValue} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.visionai.v1alpha1.AttributeValue, 3));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.AttributeValue|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.setDefaultValue = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.clearDefaultValue = function() {
  return this.setDefaultValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition.prototype.hasDefaultValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string operator = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.getOperator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.setOperator = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ArgumentDefinition input_args = 2;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.getInputArgsList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition, 2));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.setInputArgsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.addInputArgs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.clearInputArgsList = function() {
  return this.setInputArgsList([]);
};


/**
 * repeated ArgumentDefinition output_args = 3;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.getOutputArgsList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition, 3));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.setOutputArgsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.addOutputArgs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.ArgumentDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.clearOutputArgsList = function() {
  return this.setOutputArgsList([]);
};


/**
 * repeated AttributeDefinition attributes = 4;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition>}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.getAttributesList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition, 4));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.setAttributesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.addAttributes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.cloud.visionai.v1alpha1.OperatorDefinition.AttributeDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.clearAttributesList = function() {
  return this.setAttributesList([]);
};


/**
 * optional ResourceSpecification resources = 5;
 * @return {?proto.google.cloud.visionai.v1alpha1.ResourceSpecification}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.getResources = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.ResourceSpecification} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.visionai.v1alpha1.ResourceSpecification, 5));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.ResourceSpecification|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.setResources = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.OperatorDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.clearResources = function() {
  return this.setResources(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.OperatorDefinition.prototype.hasResources = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.ResourceSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    cpu: jspb.Message.getFieldWithDefault(msg, 1, ""),
    memory: jspb.Message.getFieldWithDefault(msg, 2, ""),
    gpus: jspb.Message.getFieldWithDefault(msg, 3, 0),
    latencyBudgetMs: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.ResourceSpecification;
  return proto.google.cloud.visionai.v1alpha1.ResourceSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpu(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemory(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGpus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLatencyBudgetMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.ResourceSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpu();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMemory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGpus();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getLatencyBudgetMs();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string cpu = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.getCpu = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} returns this
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.setCpu = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string memory = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.getMemory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} returns this
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.setMemory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 gpus = 3;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.getGpus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} returns this
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.setGpus = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 latency_budget_ms = 4;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.getLatencyBudgetMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ResourceSpecification} returns this
 */
proto.google.cloud.visionai.v1alpha1.ResourceSpecification.prototype.setLatencyBudgetMs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.ValueCase = {
  VALUE_NOT_SET: 0,
  I: 1,
  F: 2,
  B: 3,
  S: 4
};

/**
 * @return {proto.google.cloud.visionai.v1alpha1.AttributeValue.ValueCase}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getValueCase = function() {
  return /** @type {proto.google.cloud.visionai.v1alpha1.AttributeValue.ValueCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.AttributeValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.AttributeValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    i: jspb.Message.getFieldWithDefault(msg, 1, 0),
    f: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    b: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    s: msg.getS_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.AttributeValue;
  return proto.google.cloud.visionai.v1alpha1.AttributeValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.AttributeValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setI(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setF(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setB(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.AttributeValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.AttributeValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional int64 i = 1;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getI = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.setI = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.clearI = function() {
  return jspb.Message.setOneofField(this, 1, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.hasI = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float f = 2;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getF = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.setF = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.clearF = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.hasF = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool b = 3;
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getB = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.setB = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.clearB = function() {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.hasB = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes s = 4;
 * @return {!(string|Uint8Array)}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getS = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes s = 4;
 * This is a type-conversion wrapper around `getS()`
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getS_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getS()));
};


/**
 * optional bytes s = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getS()`
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.getS_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getS()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.setS = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.AttributeValue} returns this
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.clearS = function() {
  return jspb.Message.setOneofField(this, 4, proto.google.cloud.visionai.v1alpha1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AttributeValue.prototype.hasS = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    analyzer: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operator: jspb.Message.getFieldWithDefault(msg, 2, ""),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.toObject, includeInstance),
    attrsMap: (f = msg.getAttrsMap()) ? f.toObject(includeInstance, proto.google.cloud.visionai.v1alpha1.AttributeValue.toObject) : [],
    debugOptions: (f = msg.getDebugOptions()) && proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition;
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnalyzer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperator(value);
      break;
    case 3:
      var value = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 4:
      var value = msg.getAttrsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.cloud.visionai.v1alpha1.AttributeValue.deserializeBinaryFromReader, "", new proto.google.cloud.visionai.v1alpha1.AttributeValue());
         });
      break;
    case 5:
      var value = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.deserializeBinaryFromReader);
      msg.setDebugOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnalyzer();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperator();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.serializeBinaryToWriter
    );
  }
  f = message.getAttrsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.cloud.visionai.v1alpha1.AttributeValue.serializeBinaryToWriter);
  }
  f = message.getDebugOptions();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    input: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput;
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string input = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    environmentVariablesMap: (f = msg.getEnvironmentVariablesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions;
  return proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getEnvironmentVariablesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvironmentVariablesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * map<string, string> environment_variables = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.prototype.getEnvironmentVariablesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions.prototype.clearEnvironmentVariablesMap = function() {
  this.getEnvironmentVariablesMap().clear();
  return this;};


/**
 * optional string analyzer = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.getAnalyzer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.setAnalyzer = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string operator = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.getOperator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.setOperator = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated StreamInput inputs = 3;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput>}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput, 3));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.setInputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.StreamInput, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.clearInputsList = function() {
  return this.setInputsList([]);
};


/**
 * map<string, AttributeValue> attrs = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.cloud.visionai.v1alpha1.AttributeValue>}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.getAttrsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.cloud.visionai.v1alpha1.AttributeValue>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.google.cloud.visionai.v1alpha1.AttributeValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.clearAttrsMap = function() {
  this.getAttrsMap().clear();
  return this;};


/**
 * optional DebugOptions debug_options = 5;
 * @return {?proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.getDebugOptions = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions, 5));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.DebugOptions|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.setDebugOptions = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.clearDebugOptions = function() {
  return this.setDebugOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.prototype.hasDebugOptions = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    analyzersList: jspb.Message.toObjectList(msg.getAnalyzersList(),
    proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.AnalysisDefinition;
  return proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition;
      reader.readMessage(value,proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.deserializeBinaryFromReader);
      msg.addAnalyzers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnalyzersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AnalyzerDefinition analyzers = 1;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition>}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.getAnalyzersList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition, 1));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition} returns this
*/
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.setAnalyzersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition}
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.addAnalyzers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.visionai.v1alpha1.AnalyzerDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.AnalysisDefinition} returns this
 */
proto.google.cloud.visionai.v1alpha1.AnalysisDefinition.prototype.clearAnalyzersList = function() {
  return this.setAnalyzersList([]);
};


goog.object.extend(exports, proto.google.cloud.visionai.v1alpha1);
