// source: google/cloud/visionai/v1alpha1/lva_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_cloud_visionai_v1alpha1_lva_resources_pb = require('../../../../google/cloud/visionai/v1alpha1/lva_resources_pb.js');
goog.object.extend(proto, google_cloud_visionai_v1alpha1_lva_resources_pb);
var google_longrunning_operations_pb = require('../../../../google/longrunning/operations_pb.js');
goog.object.extend(proto, google_longrunning_operations_pb);
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
goog.object.extend(proto, google_protobuf_field_mask_pb);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.GetOperatorRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest', null, global);
goog.exportSymbol('proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.displayName = 'proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.GetOperatorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.GetOperatorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.displayName = 'proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.displayName = 'proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    filter: jspb.Message.getFieldWithDefault(msg, 4, ""),
    orderBy: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest;
  return proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilter(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFilter();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOrderBy();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 page_size = 2;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string page_token = 3;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string filter = 4;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.getFilter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.setFilter = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string order_by = 5;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.getOrderBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsRequest.prototype.setOrderBy = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    operatorsList: jspb.Message.toObjectList(msg.getOperatorsList(),
    google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.toObject, includeInstance),
    nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    unreachableList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse;
  return proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Operator;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.deserializeBinaryFromReader);
      msg.addOperators(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addUnreachable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperatorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.serializeBinaryToWriter
    );
  }
  f = message.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUnreachableList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * repeated Operator operators = 1;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.Operator>}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.getOperatorsList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.Operator>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Operator, 1));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.Operator>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
*/
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.setOperatorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.Operator=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.Operator}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.addOperators = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.visionai.v1alpha1.Operator, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.clearOperatorsList = function() {
  return this.setOperatorsList([]);
};


/**
 * optional string next_page_token = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.setNextPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string unreachable = 3;
 * @return {!Array<string>}
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.getUnreachableList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.setUnreachableList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.addUnreachable = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListOperatorsResponse.prototype.clearUnreachableList = function() {
  return this.setUnreachableList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.GetOperatorRequest;
  return proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.GetOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.GetOperatorRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operatorId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    operator: (f = msg.getOperator()) && google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.toObject(includeInstance, f),
    requestId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest;
  return proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperatorId(value);
      break;
    case 3:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Operator;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.deserializeBinaryFromReader);
      msg.setOperator(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperatorId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOperator();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.serializeBinaryToWriter
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string operator_id = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.getOperatorId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.setOperatorId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Operator operator = 3;
 * @return {?proto.google.cloud.visionai.v1alpha1.Operator}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.getOperator = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.Operator} */ (
    jspb.Message.getWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Operator, 3));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.Operator|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.setOperator = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.clearOperator = function() {
  return this.setOperator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.hasOperator = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string request_id = 4;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateOperatorRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    updateMask: (f = msg.getUpdateMask()) && google_protobuf_field_mask_pb.FieldMask.toObject(includeInstance, f),
    operator: (f = msg.getOperator()) && google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.toObject(includeInstance, f),
    requestId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest;
  return proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_field_mask_pb.FieldMask;
      reader.readMessage(value,google_protobuf_field_mask_pb.FieldMask.deserializeBinaryFromReader);
      msg.setUpdateMask(value);
      break;
    case 2:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Operator;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.deserializeBinaryFromReader);
      msg.setOperator(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdateMask();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_field_mask_pb.FieldMask.serializeBinaryToWriter
    );
  }
  f = message.getOperator();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Operator.serializeBinaryToWriter
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional google.protobuf.FieldMask update_mask = 1;
 * @return {?proto.google.protobuf.FieldMask}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.getUpdateMask = function() {
  return /** @type{?proto.google.protobuf.FieldMask} */ (
    jspb.Message.getWrapperField(this, google_protobuf_field_mask_pb.FieldMask, 1));
};


/**
 * @param {?proto.google.protobuf.FieldMask|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.setUpdateMask = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.clearUpdateMask = function() {
  return this.setUpdateMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.hasUpdateMask = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Operator operator = 2;
 * @return {?proto.google.cloud.visionai.v1alpha1.Operator}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.getOperator = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.Operator} */ (
    jspb.Message.getWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Operator, 2));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.Operator|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.setOperator = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.clearOperator = function() {
  return this.setOperator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.hasOperator = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string request_id = 3;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateOperatorRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    requestId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest;
  return proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string request_id = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.DeleteOperatorRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    filter: jspb.Message.getFieldWithDefault(msg, 4, ""),
    orderBy: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest;
  return proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilter(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFilter();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOrderBy();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 page_size = 2;
 * @return {number}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string page_token = 3;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string filter = 4;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.getFilter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.setFilter = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string order_by = 5;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.getOrderBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesRequest.prototype.setOrderBy = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    analysesList: jspb.Message.toObjectList(msg.getAnalysesList(),
    google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.toObject, includeInstance),
    nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    unreachableList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse;
  return proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.deserializeBinaryFromReader);
      msg.addAnalyses(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addUnreachable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnalysesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.serializeBinaryToWriter
    );
  }
  f = message.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUnreachableList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * repeated Analysis analyses = 1;
 * @return {!Array<!proto.google.cloud.visionai.v1alpha1.Analysis>}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.getAnalysesList = function() {
  return /** @type{!Array<!proto.google.cloud.visionai.v1alpha1.Analysis>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis, 1));
};


/**
 * @param {!Array<!proto.google.cloud.visionai.v1alpha1.Analysis>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
*/
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.setAnalysesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.visionai.v1alpha1.Analysis=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.Analysis}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.addAnalyses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.visionai.v1alpha1.Analysis, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.clearAnalysesList = function() {
  return this.setAnalysesList([]);
};


/**
 * optional string next_page_token = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.setNextPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string unreachable = 3;
 * @return {!Array<string>}
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.getUnreachableList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.setUnreachableList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.addUnreachable = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse} returns this
 */
proto.google.cloud.visionai.v1alpha1.ListAnalysesResponse.prototype.clearUnreachableList = function() {
  return this.setUnreachableList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest;
  return proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.GetAnalysisRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    analysisId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    analysis: (f = msg.getAnalysis()) && google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.toObject(includeInstance, f),
    requestId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest;
  return proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnalysisId(value);
      break;
    case 3:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.deserializeBinaryFromReader);
      msg.setAnalysis(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAnalysisId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAnalysis();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.serializeBinaryToWriter
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string analysis_id = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.getAnalysisId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.setAnalysisId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Analysis analysis = 3;
 * @return {?proto.google.cloud.visionai.v1alpha1.Analysis}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.getAnalysis = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.Analysis} */ (
    jspb.Message.getWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis, 3));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.Analysis|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.setAnalysis = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.clearAnalysis = function() {
  return this.setAnalysis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.hasAnalysis = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string request_id = 4;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.CreateAnalysisRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    updateMask: (f = msg.getUpdateMask()) && google_protobuf_field_mask_pb.FieldMask.toObject(includeInstance, f),
    analysis: (f = msg.getAnalysis()) && google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.toObject(includeInstance, f),
    requestId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest;
  return proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_field_mask_pb.FieldMask;
      reader.readMessage(value,google_protobuf_field_mask_pb.FieldMask.deserializeBinaryFromReader);
      msg.setUpdateMask(value);
      break;
    case 2:
      var value = new google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis;
      reader.readMessage(value,google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.deserializeBinaryFromReader);
      msg.setAnalysis(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdateMask();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_field_mask_pb.FieldMask.serializeBinaryToWriter
    );
  }
  f = message.getAnalysis();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis.serializeBinaryToWriter
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional google.protobuf.FieldMask update_mask = 1;
 * @return {?proto.google.protobuf.FieldMask}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.getUpdateMask = function() {
  return /** @type{?proto.google.protobuf.FieldMask} */ (
    jspb.Message.getWrapperField(this, google_protobuf_field_mask_pb.FieldMask, 1));
};


/**
 * @param {?proto.google.protobuf.FieldMask|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.setUpdateMask = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.clearUpdateMask = function() {
  return this.setUpdateMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.hasUpdateMask = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Analysis analysis = 2;
 * @return {?proto.google.cloud.visionai.v1alpha1.Analysis}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.getAnalysis = function() {
  return /** @type{?proto.google.cloud.visionai.v1alpha1.Analysis} */ (
    jspb.Message.getWrapperField(this, google_cloud_visionai_v1alpha1_lva_resources_pb.Analysis, 2));
};


/**
 * @param {?proto.google.cloud.visionai.v1alpha1.Analysis|undefined} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} returns this
*/
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.setAnalysis = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.clearAnalysis = function() {
  return this.setAnalysis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.hasAnalysis = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string request_id = 3;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.UpdateAnalysisRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    requestId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest;
  return proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string request_id = 2;
 * @return {string}
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest} returns this
 */
proto.google.cloud.visionai.v1alpha1.DeleteAnalysisRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.google.cloud.visionai.v1alpha1);
